"""Provenance: where did this data come from, and what may be claimed about it?

Three claims are tracked separately, because conflating them is the main
scientific risk in this project:

1. **biological data** — a published measurement of which neurons connect to
   which. The user supplies the file; FlyBrain never downloads it.
2. **derived graph representation** — a :class:`~flybrain.brain.graph.BrainGraph`
   built from such data. A faithful re-encoding of structure, and still not a
   model.
3. **simulated neural activity** — numbers produced by integrating a dynamics
   model. Never a recording from a real fly.
4. **learned AI behaviour** — weights produced by an optimiser. Nothing to do
   with biology.

Every field a source does not provide stays ``None``. Nothing is inferred from a
filename, and in particular a file called ``flywire.csv`` is **not** treated as
biological data unless the importer was explicitly told it is.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

__all__ = [
    "BIOLOGICAL_LABEL",
    "SYNTHETIC_LABEL",
    "TEST_FIXTURE_LABEL",
    "Provenance",
    "ProvenanceError",
    "DataSource",
    "biological_label",
    "utc_timestamp",
]

#: Banner for anything derived from a real, published connectome.
BIOLOGICAL_LABEL = "Biological connectome data"

#: Banner for anything generated by this project rather than measured.
SYNTHETIC_LABEL = "Synthetic / simulated"

#: Banner for the hand-made files under ``tests/fixtures``.
TEST_FIXTURE_LABEL = "TEST FIXTURE - NOT REAL BIOLOGICAL DATA"


class ProvenanceError(ValueError):
    """Raised when provenance is internally inconsistent."""


class DataSource(str, Enum):
    """Where a dataset came from.

    Only :attr:`EXTERNAL` and :attr:`FLYWIRE` can ever yield
    ``is_biological=True``; :attr:`SYNTHETIC` and :attr:`TEST_FIXTURE` are
    structurally incapable of it, so a mislabelled fixture cannot be reported as
    real data.
    """

    SYNTHETIC = "synthetic"
    TEST_FIXTURE = "test_fixture"
    FLYWIRE = "flywire"
    EXTERNAL = "external"

    @property
    def can_be_biological(self) -> bool:
        return self not in (DataSource.SYNTHETIC, DataSource.TEST_FIXTURE)

    @property
    def label(self) -> str:
        if self is DataSource.TEST_FIXTURE:
            return TEST_FIXTURE_LABEL
        if self is DataSource.SYNTHETIC:
            return SYNTHETIC_LABEL
        return BIOLOGICAL_LABEL


def utc_timestamp() -> str:
    """Current UTC time as an ISO-8601 string, for the ``imported_at`` field."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def biological_label(is_biological: bool, source: DataSource | str | None = None) -> str:
    """Banner string for reports and figures."""
    try:
        key = source if isinstance(source, DataSource) else DataSource(str(source)) if source else None
    except ValueError:
        key = None
    if key is not None and not key.can_be_biological:
        return key.label
    return BIOLOGICAL_LABEL if is_biological else SYNTHETIC_LABEL


@dataclass
class Provenance:
    """Attribution record attached to every imported dataset.

    Unknown fields stay ``None``. :meth:`missing_fields` lists them so a report
    can state plainly what is not known, instead of leaving a blank field that
    reads as if it were verified.
    """

    source_name: str
    dataset_name: str
    source: DataSource = DataSource.EXTERNAL
    dataset_version: str | None = None
    source_url: str | None = None
    license: str | None = None
    citation: str | None = None
    imported_at: str | None = None
    original_filename: str | None = None
    biological_data: bool = True
    notes: str = ""
    attributes: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not str(self.source_name).strip():
            raise ProvenanceError("source_name is required and must not be empty")
        if not str(self.dataset_name).strip():
            raise ProvenanceError("dataset_name is required and must not be empty")
        if not isinstance(self.source, DataSource):
            self.source = DataSource(str(self.source))
        if not self.source.can_be_biological and self.biological_data:
            # Structural guard: a fixture or synthetic dataset can never claim to
            # be biological, whatever the caller asked for.
            self.biological_data = False
        if self.imported_at is None:
            self.imported_at = utc_timestamp()

    # ------------------------------------------------------------------ state

    @property
    def is_biological(self) -> bool:
        """True only when biological status was declared *and* the source allows it."""
        return bool(self.biological_data) and self.source.can_be_biological

    @property
    def label(self) -> str:
        return self.source.label if not self.source.can_be_biological else biological_label(self.is_biological)

    @property
    def is_test_fixture(self) -> bool:
        return self.source is DataSource.TEST_FIXTURE

    def missing_fields(self) -> list[str]:
        """Provenance fields the source did not provide. Never guessed."""
        optional = {
            "dataset_version": self.dataset_version,
            "source_url": self.source_url,
            "license": self.license,
            "citation": self.citation,
            "original_filename": self.original_filename,
        }
        return [name for name, value in optional.items() if value in (None, "")]

    def warning(self) -> str:
        """One-line provenance caveat that must accompany derived artefacts."""
        if self.is_biological:
            gap = self.missing_fields()
            suffix = f" (not provided: {', '.join(gap)})" if gap else ""
            return f"[{BIOLOGICAL_LABEL}] source='{self.source_name}' version={self.dataset_version or 'unknown'}{suffix}"
        if self.source is DataSource.TEST_FIXTURE:
            return f"[{TEST_FIXTURE_LABEL}] source='{self.source_name}'; statistics are not biology."
        return f"[{SYNTHETIC_LABEL}] source='{self.source_name}'; no biological claim is made."

    # ------------------------------------------------------------ round trips

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["source"] = self.source.value
        payload["is_biological"] = self.is_biological
        payload["label"] = self.label
        payload["missing_fields"] = self.missing_fields()
        return payload

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "Provenance":
        known = set(cls.__dataclass_fields__)
        kwargs = {str(k): v for k, v in payload.items() if str(k) in known}
        kwargs.setdefault("source_name", "unknown")
        kwargs.setdefault("dataset_name", "unknown")
        return cls(**kwargs)

    def save(self, path: str | Path) -> Path:
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(self.to_dict(), indent=2, sort_keys=True), encoding="utf-8")
        return target

    @classmethod
    def load(cls, path: str | Path) -> "Provenance":
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            raise ProvenanceError(f"{path} does not contain a provenance mapping")
        return cls.from_dict(payload)
